### ISSUE TITLE
无法对MythicMobs实体生效

### ISSUE THREAD

**Issue by ZeroExact** [4o4E/EClean#11]
只要是mm实体就直接被忽略了，普通生物倒是没问题
paper 1.20.1

**Comment by 4o4E** [comment]
如果mm实体是实际的实体（bukkit的）那么不会不生效（检查你的配置）

如果是虚拟实体（发包实现的）那么不会，不该，也不可能生效

**Comment by ZeroExact** [comment]
mm是实际的实体，clearlagg可以正常限制，mm版本为5.3.5

**Comment by 4o4E** [comment]
是否尝试过修改settings内容

https://github.com/4o4E/EClean/blob/main/src/main/resources/config.yml#L33

**Comment by ZeroExact** [comment]
经过排查发现只要MM去掉怪物名称即可正常清理
ECL配置文件如下
```
# 区块检查(密集实体清理)
chunk:
  enable: true
  disable_world:
    - "不清理的世界"
  finish: ""
  settings:
    name: true
    lead: false
    mount: false
  count: 50
  format: "{chunk}中{entity}的数量较多({count})"
  limit:
    HUSK: 4
```

chunk.settings.name一项似乎是无效的
